### ISSUE TITLE
refactor/feature: command line arg parsing

### ISSUE THREAD

**Issue by garfr** [bonlang/bonc#6]
While functional, the current arg parser is very loose and lets nonsense arguments through.  It is also very manual, and can probably be abstracted away into an API that makes it easy to add and remove args.  There are several options for implementing this:

| Method | Pros | Cons |
| ----------- | ----------- | ---- |
| GNU getopt | Optional args | Non-standardized, no long flags |
| POSIX getopt| Standardized | All of GNU getopts problems, and no optional args |
| GNU getopt_long | Supports long flags, optional args | Non-standardized |
| https://github.com/raystubbs/line-arg | Long args, optional args, arg groups | An extra dependency (though it's written in C99) |
| Custom | Anything we want, should be pretty straightforward | More implementation work, without effort upfront adding args might be painful |

Part of me leans towards just using POSIX getopt, using a dead-simple command-line interface, and having a good help print out.  I don't mind short args at all, but others may have more opinions.

**Comment by wooosh** [comment]
closes #6

**Comment by garfr** [comment]
We ended up going with a custom arg parser which should make customizing our command line interface much easier.
